### ISSUE TITLE
NAT64 considerations

### ISSUE THREAD

**Issue by danwing** [ronbonica/ICMP#1]
Should consider adding issues related to IPv6/IPv4 stateless and stateful translation, such as IPv6 message length

**Comment by ronbonica** [comment]
I added an empty section for translation issues. Please add text and add yourself to the author list.

**Comment by ronbonica** [comment]
Dan,

The text looks good, but wouldn't you like to add yourself to the author list?

                                                           Ron



Juniper Business Use Only

________________________________
